#!/bin/bash

REPOSITORY=./repo


PLUGINS=$(echo plugin.video.*)

echo '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' > ./addons.xml
cat ./repository.finnish-tv/addon.xml | grep -v "<?xml" >> ./addons.xml
echo "<addons>" >> ./addons.xml
echo "making release zip files..."

for i in $PLUGINS
do
	echo "check if version of plugin $i exists on repo"
	VERSION=$(xpath -q -e "/addon/attribute::version" $i/addon.xml | awk -F\" '{ print $2 }')
	REPOFILE=$REPOSITORY/$i/$i-$VERSION.zip
	if [ -f $REPOFILE ]
	then
		echo "file exists"
	else
		echo "file does not exist"
		zip -r $REPOFILE $i -x@.gitignore > /dev/null
	fi
	cat $i/addon.xml | grep -v "<?xml" >> ./addons.xml
done
echo "</addons>" >> ./addons.xml
md5sum addons.xml > addons.xml.md5

#zip -r $REPOSITORY/repository.finnish-tv/repository.finnish-tv-1.0.0.zip repository.finnish.tv
